### ISSUE TITLE
[REJECTED] Update?

### ISSUE THREAD

**Issue by sergeevabc** [timdream/google-apps-openid#1]
Login failed: The OpenID Provider issued an assertion for an Identifier whose discovery information did not match.
Assertion endpoint info:
ClaimedIdentifier: http://......com/openid?id=114837533887616546096
ProviderLocalIdentifier: http://......com/openid?id=114837533887616546096
ProviderEndpoint: https://www.google.com/a/......com/o8/ud?be=o8
OpenID version: 2.0 Service Type URIs: Discovered endpoint info: []

**Comment by timdream** [comment]
@sergeevabc, this project was work of my previous, previous job. I no longer have the capacity to maintain it. You are very welcome to fork away and make improvements.

**Comment by sergeevabc** [comment]
@timdream, thank you for a quick reply.

I hoped you knew what happened with Google OpenID as they changed something.
There is a burst of indignation around, topic search results are full of confusion, and no solution is obvious.
